# Update this file to add the content
version: '3'
services :
  Siva_Personal_api :
     image : "sivachidhambaram27/22it047-personal-api.py-docker"
     container_name : siva_personal_api_container
     restart : always
     ports :
       - "5001:5000"
  Siva_ml-model :
     image : "sivachidhambaram27/22it047-ml-model.py-docker"
     container_name : siva_ml-model_container
     restart : always
     ports :
       - "5002:5000"
  Saran_ml_model :
      image: "ssaran2701/ml-model.py"
      container_name : saran_ml_model_container
      restart : always
      ports :
        - "5003:5000"